"""empty message

Revision ID: 18195ddde840
Revises: 1b98b61ed1a1
Create Date: 2021-01-09 22:10:34.663216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18195ddde840'
down_revision = '1b98b61ed1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
